### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by IgorTkachuk** [IgorTkachuk/homepage#5]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by tka4yk** [comment]
#### PERSONAL LIFE

<small>2006</small>  
Melania gained United States citizenship and gave birth to our son, Barron

<small>2005</small>  
Married her

<small>1998</small>  
Met my future third wife, Melania Knauss

<small>1999</small>  
Divorced Marla ¯\_(ツ)_/¯

<small>1993</small>  
Married Marla and had a daughter, we named her Tiffany, because I like Tiffany & Company jewellery as well

<small>1992</small>  
Started affair with Marla Maples, so I had to divorce. God knows I love nice women, I love them all!

<small>1984</small>  
Birth of Eric Trump

<small>1982</small>  
Birth of Ivanka Trump

<small>1977</small>  
My first son is born. I called him Donald, of course!

<small>1977</small>  
Married Czech model Ivana Zelníčková


#### MEDIA CAREER

<small>2019</small>  
Was awarded Worst Actor and Worst Screen Combo at Golden Raspberry Awards for parts in "Death of a Nation" and "Fahrenheit 11/9"

<small>2015</small>  
Published a book "Crippled America: How to Make America Great Again"

<small>2011</small>  
Published a book "Time to Get Tough: Making America #1 Again" in coauthorship with Wynton Hall, Peter Schweizer and Meredith McIver

<small>2011</small>  
Published a book "Midas Touch: Why Some Entrepreneurs Get Rich – And Why Most Don't" in coauthorship with Robert Kiyosaki

<small>2011</small>  
Published a book "Trump Tower" in coauthorship with Jeffrey Robinson

<small>2009</small>  
Published a book "Think Like a Champion: An Informal Education in Business and Life" in coauthorship with Meredith McIver

<small>2008</small>  
Published a book "Never Give Up: How I Turned My Biggest Challenges into Success" in coauthorship with Meredith McIver

<small>2007</small>  
Published a book "Think Big and Kick Ass" in coauthorship with Bill Zanker

<small>2007</small>  
Received a star on the Hollywood Walk of Fame for being producer of Miss Universe pageant

<small>2006</small>  
Published a book "Why We Want You to Be Rich" in coauthorship with  Meredith McIver and Robert Kiyosaki

<small>2006</small>  
Published a book "How to Build a Fortune: Your Plan for Success From the World's Most Famous Businessman"

<small>2006</small>  
Published a book "The Best Real Estate Advice I Ever Received: 100 Top Experts Share Their Strategies"

<small>2006</small>  
Published a book "Trump 101: The Way to Success" in coauthorship with Meredith McIver

<small>2005</small>  
Published a book "The Best Golf Advice I Ever Received"

<small>2005</small>  
Performed a song with Megan Mullally at the 57th Primetime Emmy Awards

<small>2004 ― 2008</small>  
Ran short-form talk radio program "Trumped!" (one to two minutes on weekdays)

<small>2004</small>  
Published a book "Trump: How to Get Rich" in coauthorship with Meredith McIver

<small>2004</small>  
Published a book "The Way to the Top: The Best Business Advice I Ever Received"

<small>2004</small>  
Published a book "Think Like a Billionaire: Everything You Need to Know About Success, Real Estate, and Life" in coauthorship with Meredith McIver

<small>2003 ― 2015</small>  
Produced NBC reality shows "The Apprentice" and "The Celebrity Apprentice"

<small>2000</small>  
Published a book "Trump: The America We Deserve" in coauthorship with Dave Shiflett

<small>1997</small>  
Published a book "Trump: The Art of the Comeback" in coauthorship with Kate Bohner

<small>1991</small>  
Was awarded Worst Supporting Actor at Golden Raspberry Awards for a part in "Ghosts Can't Do It"

<small>1990</small>  
Published a book "Trump: Surviving at the Top" in coauthorship with Charles Leerhsen

<small>1987</small>  
Published a book "Trump: The Art of the Deal" in coauthorship with Tony Shwartz


#### EDUCATION

<small>2011</small>  
Asked friends who are prominent and wealthy alumni of the New York Military Academy to secure my academic records so they could not be seen by anyone, never!  

<small>1966</small>  
Transferred to the Wharton School of the University of Pennsylvania and graduated in May 1968 with a B.S. in economics  

<small>1964</small>  
Started studying in Fordham University  

<small>1959</small>  
Enrolled in the New York Military Academy, a private boarding school, after my parents discovered I made frequent trips into Manhattan without their permission  


#### LANGUAGES
🇺🇸 ENGLISH 🇷🇺 РУССКИЙ

#### SKILLS 

NEGOTIATING COUNTING REMODELING WRITING ACING SINGING REPORTING INCORPORATING SELLING ADVERTISING HOSTING COMPETING TWITTING PARENTING GAMBLING DATING SUING ORGANIZING FUNDING DEBATING ADVISING PRESBYTERIANING 

#### CHARACTER  

ADJUSTED CALM AMBITIOUS COMPETITIVE SOCIABLE DIRECT HOSTILE CARELESS IGNORANT INQUISITIVE BOLD CONFIDENT MISCHIEVOUS CHARMING INTERESTING DARING COLORFUL LAZY SELF-PROMOTING

#### LIKES 😃  

<a href="https://www.youtube.com/watch?v=u_aLESDql1U" rel="external">BILLIONS</a> FILET-O-FISH BIG MAC <a href="https://www.youtube.com/watch?v=RDrfE9I8_hs" rel="external">CHINA</a> QUARTER POUNDER DIET COKE TARIFFS BIBLE ARTOF DEAL PATRIOTS BEAUTIFUL MODELS GOLD REAL ESTATE WAR PROTESTERS CONSTRUCTION RUSSIANS BANKS SPORTS WOMEN MEXICO RED HAT KOREANS GOLF EVERYBODY <sup><a href="https://www.youtube.com/watch?v=0f9ysmciWUk" rel="external">[1]</a> <a href="https://www.youtube.com/watch?v=TTdmKaXAfAs">[2]</a></sup>

#### DISLIKES 😞  

DOGS MEDIA CNN GERMANS MEXICANS IMMIGRANTS SHITHOLE COUNTRIES UNATTRACTIVE WOMEN BLACKS SUSHI HOT-DOGS ALCOHOL FRUIT CHRISTMAS PARTIES LIBERALS 

#### WANTS 🥺
BE HEALTHY GROW A TREE BUILD TRUMP AIRPORT HAVE A TASTE DO A HARLEM SHAKE IN CONGRESS TO GOLF MORE OFTEN WIN ALL THE COURT SUITS

**Comment by IgorTkachuk** [comment]
Thank you!!
